/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js normally.
// It is included here so the starter archive opens cleanly in editors.
