export const databaseTables = [
  'app_settings',
  'profiles',
  'sources',
  'funnel_stages',
  'tags',
  'leads',
  'lead_tags',
  'lead_interactions',
  'tasks',
  'task_assignees',
  'surveys',
  'survey_questions',
  'survey_answers',
  'campaigns',
  'campaign_leads',
  'insights',
  'insight_leads',
  'insight_campaigns',
  'insight_surveys',
  'hypotheses',
  'hypothesis_leads',
  'hypothesis_insights',
  'hypothesis_campaigns',
  'hypothesis_surveys',
  'lead_questionnaires',
  'lead_questionnaire_questions',
  'lead_questionnaire_answers',
  'question_packs',
  'question_pack_questions',
  'message_templates',
  'refusal_reasons',
  'saved_lead_views',
  'import_logs',
  'activity_logs',
  'notification_reads',
  'telegram_delivery_logs'
] as const;

export type DatabaseTable = (typeof databaseTables)[number];

export const workDataTables = [
  'telegram_delivery_logs',
  'notification_reads',
  'saved_lead_views',
  'import_logs',
  'lead_questionnaire_answers',
  'lead_questionnaire_questions',
  'lead_questionnaires',
  'survey_answers',
  'survey_questions',
  'hypothesis_leads',
  'hypothesis_insights',
  'hypothesis_campaigns',
  'hypothesis_surveys',
  'insight_leads',
  'insight_campaigns',
  'insight_surveys',
  'campaign_leads',
  'lead_tags',
  'lead_interactions',
  'task_assignees',
  'tasks',
  'hypotheses',
  'insights',
  'campaigns',
  'surveys',
  'leads'
] as const;

export const directoryDataTables = [
  'question_pack_questions',
  'question_packs',
  'message_templates',
  'refusal_reasons',
  'tags',
  'sources',
  'funnel_stages'
] as const;

export const databaseTableLabels: Record<(typeof databaseTables)[number], string> = {
  app_settings: 'Настройки приложения',
  profiles: 'Профили',
  sources: 'Источники',
  funnel_stages: 'Стадии',
  tags: 'Теги',
  leads: 'Контакты',
  lead_tags: 'Теги контактов',
  lead_interactions: 'История контактов',
  tasks: 'Задачи',
  task_assignees: 'Участники задач',
  surveys: 'Анкеты',
  survey_questions: 'Вопросы анкет',
  survey_answers: 'Ответы анкет',
  campaigns: 'Кампании',
  campaign_leads: 'Контакты кампаний',
  insights: 'Выводы',
  insight_leads: 'Связи выводов с контактами',
  insight_campaigns: 'Связи выводов с кампаниями',
  insight_surveys: 'Связи выводов с анкетами',
  hypotheses: 'Проверки',
  hypothesis_leads: 'Проверки по контактам',
  hypothesis_insights: 'Проверки по выводам',
  hypothesis_campaigns: 'Проверки по кампаниям',
  hypothesis_surveys: 'Проверки по анкетам',
  lead_questionnaires: 'Вопросы для контакта',
  lead_questionnaire_questions: 'Вопросы контакта',
  lead_questionnaire_answers: 'Ответы контакта',
  question_packs: 'Готовые вопросы',
  question_pack_questions: 'Вопросы в готовых вопросах',
  message_templates: 'Шаблоны сообщений',
  refusal_reasons: 'Причины отказов',
  saved_lead_views: 'Сохраненные виды',
  import_logs: 'Логи импорта',
  activity_logs: 'Логи действий',
  notification_reads: 'Прочтения уведомлений',
  telegram_delivery_logs: 'Telegram-логи'
};
